from app.macro.candidate_behavior import (
    MACRO_CANDIDATE_BEHAVIOR_CONTRACT_VERSION,
    MACRO_CANDIDATE_BEHAVIOR_GROUP_CONTRACT_VERSION,
    build_candidate_behavior,
    build_behavior_groups,
    build_method_overlap_matrix,
)
from app.macro.candidate_compression import (
    MACRO_COMPRESSED_CANDIDATE_SET_CONTRACT_VERSION,
    MACRO_COMPRESSION_CONTRACT_VERSION,
    MACRO_CROSS_METHOD_DOMINANCE_CONTRACT_VERSION,
    build_compressed_candidate_frontier,
    pareto_prune_behavior_groups,
    summarize_compressed_frontier,
    validate_compressed_frontier_artifact,
)
from app.macro.calibration_candidate import (
    MACRO_CANDIDATE_SET_CONTRACT_VERSION,
    MACRO_CANDIDATE_GENERATION_CONTRACT_VERSION,
    MACRO_RATE_SPIKE_CANDIDATE_CONTRACT_VERSION,
    RATE_SPIKE_FEATURE_IDS,
    RATE_SPIKE_METHODS,
    build_rate_spike_candidate_set,
    evaluate_candidate_behavior,
    generate_feature_candidates,
    generate_raw_feature_candidates,
    summarize_candidate_set,
    validate_candidate_set_artifact,
)
from app.macro.candidate_selection import (
    MACRO_CANDIDATE_DOMINANCE_CONTRACT_VERSION,
    pareto_prune_candidates,
)
from app.macro.shock_episode import (
    RATE_SPIKE_EPISODE_POLICY_VERSION,
    build_consecutive_true_episodes,
)
from app.macro.calibration_research import (
    MACRO_DISTRIBUTION_RESEARCH_CONTRACT_VERSION,
    build_distribution_research,
    summarize_distribution_research,
    validate_development_artifact,
    validate_distribution_research_artifact,
    validate_research_protocol,
)
from app.macro.distribution import (
    MACRO_DISTRIBUTION_CONTRACT_VERSION,
    RESEARCH_FEATURE_IDS,
    analyze_feature_distribution,
    build_expanding_analysis,
    build_yearly_summary,
    empirical_cdf,
    median_absolute_deviation,
    summarize_values,
    tail_profile,
)
from app.macro.calibration_dataset import (
    MACRO_CALIBRATION_DATASET_CONTRACT_VERSION,
    CalibrationSplitRole,
    build_calibration_dataset,
)
from app.macro.calibration_protocol import (
    MACRO_CALIBRATION_PROTOCOL_CONTRACT_VERSION,
    MacroCalibrationProtocol,
    build_calibration_research_protocol,
    validate_split_ranges,
)
from app.macro.calibration import (
    CalibrationStatus,
    MacroShockCalibration,
    uncalibrated_rate_spike_calibration,
)
from app.macro.context import (
    MACRO_CONTEXT_CONTRACT_VERSION,
    MacroContextStatus,
    MacroContextUsage,
    build_macro_context,
)
from app.macro.reference_diagnostic import (
    REFERENCE_DIAGNOSTIC_AS_OF,
    REFERENCE_DIAGNOSTIC_CONTRACT_VERSION,
    REFERENCE_DIAGNOSTIC_RETROSPECTIVE,
    build_as_of_reference_diagnostic,
    build_retrospective_reference_diagnostic,
    validate_reference_diagnostic,
)
from app.macro.features import (
    MACRO_FEATURE_CONTRACT_VERSION,
    MacroFeature,
    MacroFeatureStatus,
    build_dgs10_features,
)
from app.macro.contract import (
    EvidenceTimeQuality,
    MacroObservation,
    MacroResearchProtocol,
    MacroSeriesContract,
    TemporalEvidence,
    fred_dgs10_candidate_contract,
    fred_dgs10_research_contract,
)
from app.macro.errors import MacroContractError
from app.macro.manifest import MacroPreparedRangeManifest
from app.macro.reader import LocalMacroReader
from app.macro.shock import (
    MACRO_EPISODE_CONTRACT_VERSION,
    MACRO_SHOCK_CONTRACT_VERSION,
    ShockEpisodeContract,
    ShockState,
    ShockType,
    build_uncalibrated_shock_assessment,
)
from app.macro.store import (
    MACRO_META_EXPECTED,
    MACRO_STORE_SCHEMA_VERSION,
    MACRO_STORE_TABLES,
    MacroStore,
)

__all__ = [
    "MACRO_CANDIDATE_BEHAVIOR_CONTRACT_VERSION",
    "MACRO_CANDIDATE_BEHAVIOR_GROUP_CONTRACT_VERSION",
    "MACRO_COMPRESSED_CANDIDATE_SET_CONTRACT_VERSION",
    "MACRO_COMPRESSION_CONTRACT_VERSION",
    "MACRO_CROSS_METHOD_DOMINANCE_CONTRACT_VERSION",
    "build_candidate_behavior",
    "build_behavior_groups",
    "build_method_overlap_matrix",
    "build_compressed_candidate_frontier",
    "pareto_prune_behavior_groups",
    "summarize_compressed_frontier",
    "validate_compressed_frontier_artifact",
    "MACRO_CANDIDATE_SET_CONTRACT_VERSION",
    "MACRO_CANDIDATE_GENERATION_CONTRACT_VERSION",
    "MACRO_RATE_SPIKE_CANDIDATE_CONTRACT_VERSION",
    "MACRO_CANDIDATE_DOMINANCE_CONTRACT_VERSION",
    "RATE_SPIKE_EPISODE_POLICY_VERSION",
    "RATE_SPIKE_FEATURE_IDS",
    "RATE_SPIKE_METHODS",
    "build_rate_spike_candidate_set",
    "evaluate_candidate_behavior",
    "generate_feature_candidates",
    "generate_raw_feature_candidates",
    "summarize_candidate_set",
    "validate_candidate_set_artifact",
    "pareto_prune_candidates",
    "build_consecutive_true_episodes",
    "MACRO_DISTRIBUTION_RESEARCH_CONTRACT_VERSION",
    "MACRO_DISTRIBUTION_CONTRACT_VERSION",
    "RESEARCH_FEATURE_IDS",
    "analyze_feature_distribution",
    "build_distribution_research",
    "build_expanding_analysis",
    "build_yearly_summary",
    "empirical_cdf",
    "median_absolute_deviation",
    "summarize_distribution_research",
    "summarize_values",
    "tail_profile",
    "validate_development_artifact",
    "validate_research_protocol",
    "validate_distribution_research_artifact",
    "MACRO_CALIBRATION_DATASET_CONTRACT_VERSION",
    "MACRO_CALIBRATION_PROTOCOL_CONTRACT_VERSION",
    "CalibrationSplitRole",
    "MacroCalibrationProtocol",
    "build_calibration_dataset",
    "build_calibration_research_protocol",
    "validate_split_ranges",
    "CalibrationStatus",
    "MACRO_CONTEXT_CONTRACT_VERSION",
    "REFERENCE_DIAGNOSTIC_AS_OF",
    "REFERENCE_DIAGNOSTIC_CONTRACT_VERSION",
    "REFERENCE_DIAGNOSTIC_RETROSPECTIVE",
    "MACRO_EPISODE_CONTRACT_VERSION",
    "MACRO_FEATURE_CONTRACT_VERSION",
    "MACRO_SHOCK_CONTRACT_VERSION",
    "MacroContextStatus",
    "MacroContextUsage",
    "MacroFeature",
    "MacroFeatureStatus",
    "MacroShockCalibration",
    "ShockEpisodeContract",
    "ShockState",
    "ShockType",
    "build_as_of_reference_diagnostic",
    "build_dgs10_features",
    "build_macro_context",
    "build_retrospective_reference_diagnostic",
    "build_uncalibrated_shock_assessment",
    "validate_reference_diagnostic",
    "uncalibrated_rate_spike_calibration",
    "EvidenceTimeQuality",
    "LocalMacroReader",
    "MacroContractError",
    "MacroObservation",
    "MacroPreparedRangeManifest",
    "MacroResearchProtocol",
    "MacroSeriesContract",
    "MacroStore",
    "TemporalEvidence",
    "fred_dgs10_candidate_contract",
    "fred_dgs10_research_contract",
    "MACRO_META_EXPECTED",
    "MACRO_STORE_SCHEMA_VERSION",
    "MACRO_STORE_TABLES",
]
